import {
  HomeIcon,
  UserIcon,
  UserCircleIcon,
  EnvelopeIcon,
  PhoneArrowDownLeftIcon,
  CalendarDaysIcon,
  CalendarIcon,
  UserPlusIcon,
  TrashIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  Bars3Icon,
  Bars3BottomLeftIcon,
  PlusIcon,
  PaintBrushIcon,
  ArrowDownOnSquareIcon,
  ArrowDownTrayIcon,
  ArrowUpTrayIcon,
  GlobeAltIcon,
  Cog8ToothIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  DocumentArrowDownIcon,
  EllipsisVerticalIcon,
  XMarkIcon,
  ArrowLeftEndOnRectangleIcon,
  InformationCircleIcon,
  BarsArrowDownIcon,
  BarsArrowUpIcon,
  ChevronUpDownIcon,
  FunnelIcon,
  ArrowPathIcon,
  PlusCircleIcon
} from '@heroicons/vue/20/solid'

import {
  PencilSquareIcon as PencilSquareIconOutline,
  PhotoIcon as PhotoIconOutline,
  Bars3Icon as Bars3IconOutline,
  XMarkIcon as XMarkIconOutline,
  UserIcon as UserIconOutline,
  UserCircleIcon as UserCircleIconOutline,
  EnvelopeIcon as EnvelopeIconOutline,
  PhoneIcon as PhoneIconOutline,
  CalendarDaysIcon as CalendarDaysIconOutline,
  UserPlusIcon as UserPlusIconOutline,
  MagnifyingGlassIcon as MagnifyingGlassIconOutline,
  EyeIcon as EyeIconOutline,
  TrashIcon as TrashIconOutline,
  Cog6ToothIcon as Cog6ToothIconOutline,
  Cog8ToothIcon as Cog8ToothIconOutline,
  PaintBrushIcon as PaintBrushIconOutline,
  ClipboardDocumentListIcon as ClipboardDocumentListIconOutline,
  QrCodeIcon as QrCodeIconOutline,
  GlobeAltIcon as GlobeAltIconOutline,
  DocumentDuplicateIcon as DocumentDuplicateIconOutline,
  DocumentArrowDownIcon as DocumentArrowDownIconOutline,
  PencilIcon as PencilIconOutline,
  LinkIcon as LinkIconOutline,
  UsersIcon as UsersIconOutline,
  HomeIcon as HomeIconOutline,
  UserGroupIcon as UserGroupIconOutline,
  FunnelIcon as FunnelIconOutline,
  ShoppingBagIcon as ShoppingBagIconOutline,
  CreditCardIcon as CreditCardIconOutline,
  InformationCircleIcon as InformationCircleIconOutline,
  DocumentCurrencyDollarIcon as DocumentCurrencyDollarIconOutline,
  DocumentMagnifyingGlassIcon as DocumentMagnifyingGlassIconOutline,
  LockClosedIcon as LockClosedIconOutline,
  ShieldCheckIcon as ShieldCheckIconOutline,
  DocumentTextIcon as DocumentTextIconOutline
} from '@heroicons/vue/24/outline'

const Icon = {
  HomeIcon,
  PencilSquareIconOutline,
  PhotoIconOutline,
  Bars3IconOutline,
  XMarkIconOutline,
  UserIcon,
  UserIconOutline,
  UserCircleIcon,
  UserCircleIconOutline,
  EnvelopeIconOutline,
  PhoneIconOutline,
  EnvelopeIcon,
  PhoneArrowDownLeftIcon,
  CalendarDaysIcon,
  CalendarDaysIconOutline,
  CalendarIcon,
  UserPlusIcon,
  UserPlusIconOutline,
  MagnifyingGlassIconOutline,
  EyeIconOutline,
  TrashIcon,
  TrashIconOutline,
  Cog6ToothIconOutline,
  Cog8ToothIconOutline,
  ArrowLeftIcon,
  ArrowRightIcon,
  Bars3Icon,
  PlusIcon,
  PaintBrushIcon,
  PaintBrushIconOutline,
  ClipboardDocumentListIconOutline,
  QrCodeIconOutline,
  ArrowDownOnSquareIcon,
  ArrowDownTrayIcon,
  ArrowUpTrayIcon,
  GlobeAltIconOutline,
  DocumentDuplicateIconOutline,
  GlobeAltIcon,
  Cog8ToothIcon,
  ChevronDownIcon,
  DocumentArrowDownIcon,
  DocumentArrowDownIconOutline,
  ChevronUpIcon,
  EllipsisVerticalIcon,
  PencilIconOutline,
  LinkIconOutline,
  XMarkIcon,
  UsersIconOutline,
  HomeIconOutline,
  UserGroupIconOutline,
  Bars3BottomLeftIcon,
  ArrowLeftEndOnRectangleIcon,
  InformationCircleIcon,
  BarsArrowDownIcon,
  BarsArrowUpIcon,
  ChevronUpDownIcon,
  FunnelIcon,
  FunnelIconOutline,
  ArrowPathIcon,
  ShoppingBagIconOutline,
  CreditCardIconOutline,
  InformationCircleIconOutline,
  DocumentCurrencyDollarIconOutline,
  DocumentMagnifyingGlassIconOutline,
  LockClosedIconOutline,
  ShieldCheckIconOutline,
  DocumentTextIconOutline,
  PlusCircleIcon
}

export default Icon
